Repository agentuniverse-ai/agentUniverse, pull requests merged in 2025-02, with the labels that each got.

#287 improvement: support auto-loading for agent YAML and prompt versions
  agentuniverse/base/config/component_configer/component_configer.py
  agentuniverse/base/config/component_configer/configers/agent_configer.py
  agentuniverse/base/config/component_configer/configers/prompt_configer.py
  agentuniverse/base/util/system_util.py
  agentuniverse_product/base/constant/llm_constant.py
  examples/sample_apps/peer_agent_app/intelligence/agentic/prompt/peer_agent_case/__init__.py
  examples/sample_apps/peer_agent_app/intelligence/agentic/prompt/peer_agent_case/demo_executing_agent/__init__.py
  examples/sample_apps/peer_agent_app/intelligence/agentic/prompt/peer_agent_case/demo_executing_agent/cn.yaml
  examples/sample_apps/peer_agent_app/intelligence/agentic/prompt/peer_agent_case/demo_expressing_agent/__init__.py
  examples/sample_apps/peer_agent_app/intelligence/agentic/prompt/peer_agent_case/demo_expressing_agent/cn.yaml
  examples/sample_apps/peer_agent_app/intelligence/agentic/prompt/peer_agent_case/demo_planning_agent/__init__.py
  examples/sample_apps/peer_agent_app/intelligence/agentic/prompt/peer_agent_case/demo_planning_agent/cn.yaml
  examples/sample_apps/peer_agent_app/intelligence/agentic/prompt/translation/country_multi_translation_reflection_en.yaml
  examples/sample_apps/peer_agent_app/intelligence/agentic/prompt/translation/country_translation_reflection_en.yaml
  examples/sample_apps/peer_agent_app/intelligence/agentic/prompt/translation/multi_translation_improve_en.yaml
  examples/sample_apps/peer_agent_app/intelligence/agentic/prompt/translation/multi_translation_init_en.yaml
  examples/sample_apps/peer_agent_app/intelligence/agentic/prompt/translation/multi_translation_reflection_en.yaml
  examples/sample_apps/peer_agent_app/intelligence/agentic/prompt/translation/translation_improve_en.yaml
  examples/sample_apps/peer_agent_app/intelligence/agentic/prompt/translation/translation_init_en.yaml
  examples/sample_apps/peer_agent_app/intelligence/agentic/prompt/translation/translation_reflection_en.yaml
  examples/sample_standard_app/intelligence/agentic/agent/agent_instance/demo_agent.yaml
  examples/sample_standard_app/intelligence/agentic/knowledge/rag_router/nlu_rag_router.yaml
  examples/sample_standard_app/intelligence/agentic/prompt/demo_agent/__init__.py
  examples/sample_standard_app/intelligence/agentic/prompt/demo_agent/cn.yaml
  examples/sample_standard_app/platform/difizen/product/llm/demo_llm_product.yaml
Labels: enhancement

#291 chore: Add CONTRIBUTING file & pr template
  .github/pull-request-template.md
  CONTRIBUTING.md
  CONTRIBUTING_zh.md
  docs/guidebook/en/Contents.md
Labels: chore

#312 feat: add peer cases for canvas-based development platform in aU.
  examples/sample_apps/peer_agent_app/intelligence/agentic/agent/peer_workflow.yaml
  examples/sample_apps/peer_agent_app/intelligence/agentic/tool/param_converter.py
  examples/sample_apps/peer_agent_app/intelligence/agentic/tool/param_converter.yaml
  examples/sample_apps/peer_agent_app/platform/difizen/product/agent/executing_agent_product.yaml
  examples/sample_apps/peer_agent_app/platform/difizen/product/agent/expressing_agent_product.yaml
  examples/sample_apps/peer_agent_app/platform/difizen/product/agent/peer_workflow_product.yaml
  examples/sample_apps/peer_agent_app/platform/difizen/product/agent/planning_agent_product.yaml
  examples/sample_apps/peer_agent_app/platform/difizen/product/agent/reviewing_agent_product.yaml
  examples/sample_apps/peer_agent_app/platform/difizen/product/plugin/common_plugin.yaml
  examples/sample_apps/peer_agent_app/platform/difizen/product/tool/param_converter_product.yaml
  examples/sample_apps/peer_agent_app/platform/difizen/resources/agent_logo.png
  examples/sample_apps/peer_agent_app/platform/difizen/workflow/workflow_944.yaml
Labels: feat

#308 feat: add multimodal agent examples.
  agentuniverse/agent/agent.py
  agentuniverse/base/annotation/trace.py
  agentuniverse/prompt/chat_prompt.py
  docs/guidebook/zh/开始使用/9.进阶技巧-多模态智能体.md
  examples/sample_apps/multimodal_app/__init__.py
  examples/sample_apps/multimodal_app/bootstrap/__init__.py
  examples/sample_apps/multimodal_app/bootstrap/intelligence/__init__.py
  examples/sample_apps/multimodal_app/bootstrap/intelligence/server_application.py
  examples/sample_apps/multimodal_app/config/config.toml
  examples/sample_apps/multimodal_app/config/custom_key.toml.sample
  examples/sample_apps/multimodal_app/config/gunicorn_config.toml
  examples/sample_apps/multimodal_app/config/log_config.toml
  examples/sample_apps/multimodal_app/intelligence/__init__.py
  examples/sample_apps/multimodal_app/intelligence/agentic/__init__.py
  examples/sample_apps/multimodal_app/intelligence/agentic/agent/__init__.py
  examples/sample_apps/multimodal_app/intelligence/agentic/agent/agent_instance/__init__.py
  examples/sample_apps/multimodal_app/intelligence/agentic/agent/agent_instance/multimodal_agent.py
  examples/sample_apps/multimodal_app/intelligence/agentic/agent/agent_instance/multimodal_agent.yaml
  examples/sample_apps/multimodal_app/intelligence/agentic/agent/agent_template/__init__.py
  examples/sample_apps/multimodal_app/intelligence/agentic/knowledge/__init__.py
  examples/sample_apps/multimodal_app/intelligence/agentic/knowledge/doc_processor/__init__.py
  examples/sample_apps/multimodal_app/intelligence/agentic/knowledge/query_paraphraser/__init__.py
  examples/sample_apps/multimodal_app/intelligence/agentic/knowledge/rag_router/__init__.py
  examples/sample_apps/multimodal_app/intelligence/agentic/knowledge/raw_knowledge_file/__init__.py
  examples/sample_apps/multimodal_app/intelligence/agentic/knowledge/store/__init__.py
  examples/sample_apps/multimodal_app/intelligence/agentic/llm/__init__.py
  examples/sample_apps/multimodal_app/intelligence/agentic/llm/kimi_multimodal_llm.yaml
  examples/sample_apps/multimodal_app/intelligence/agentic/llm/qwen_multimodal_llm.yaml
  examples/sample_apps/multimodal_app/intelligence/agentic/memory/__init__.py
  examples/sample_apps/multimodal_app/intelligence/agentic/memory/demo_memory.yaml
  examples/sample_apps/multimodal_app/intelligence/agentic/memory/memory_compressor/__init__.py
  examples/sample_apps/multimodal_app/intelligence/agentic/memory/memory_storage/__init__.py
  examples/sample_apps/multimodal_app/intelligence/agentic/memory/memory_storage/chroma_memory_storage.yaml
  examples/sample_apps/multimodal_app/intelligence/agentic/prompt/__init__.py
  examples/sample_apps/multimodal_app/intelligence/agentic/prompt/multimodal_agent/__init__.py
  examples/sample_apps/multimodal_app/intelligence/agentic/prompt/multimodal_agent/cn.yaml
  examples/sample_apps/multimodal_app/intelligence/agentic/tool/__init__.py
  examples/sample_apps/multimodal_app/intelligence/agentic/tool/google_search_tool.py
  examples/sample_apps/multimodal_app/intelligence/agentic/tool/google_search_tool.yaml
  examples/sample_apps/multimodal_app/intelligence/agentic/work_pattern/__init__.py
  examples/sample_apps/multimodal_app/intelligence/service/__init__.py
  examples/sample_apps/multimodal_app/intelligence/service/agent_service/__init__.py
  examples/sample_apps/multimodal_app/intelligence/service/agent_service/multimodal_service.yaml
  examples/sample_apps/multimodal_app/intelligence/service/classic_service/__init__.py
  examples/sample_apps/multimodal_app/intelligence/test/__init__.py
  examples/sample_apps/multimodal_app/intelligence/test/dog_and_girl.jpeg
  examples/sample_apps/multimodal_app/intelligence/test/multimodal_agent.py
  examples/sample_apps/multimodal_app/intelligence/utils/__init__.py
  examples/sample_apps/multimodal_app/intelligence/utils/common/__init__.py
  examples/sample_apps/multimodal_app/intelligence/utils/common/jsonl_file_util.py
  examples/sample_apps/multimodal_app/intelligence/utils/common/txt_file_util.py
Labels: enhancement
